name: Publish to Pypi
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # regex to match semantic versioning tags

jobs:
  tests:
    uses: ./.github/workflows/main.yml
  publish:
    name: publish
    needs: [main] # require main to pass before publish runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Build package
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
